In [1]:
import pandas as pd
import math

data = pd.read_csv(r'C:\Users\kevin\Documents\Personal\Athletics\SmartWatchData\SLEEP_1666271863586.csv')
data = data.iloc[:,:-21] #Get rid of the 21 unammed columns at the end of the csv file
data['naps'] = data['naps'].fillna(0)
#print(data.head())

data = data.loc[:,['date', 'naps', 'start', 'stop', 'shallowSleepTime', 'deepSleepTime', 'REMTime', 'wakeTime']]

data.start = data.start.replace(r'\+0000', '', regex=True) #clean up start and stop data
data.stop = data.stop.replace(r'\+0000', '', regex=True)

for x in data.index:
    if data.loc[x, 'naps'] != 0:
        data.loc[x, 'naps'] = str(data.loc[x, 'naps'])[23:-7]
    data.loc[x, 'start'] = str(data.loc[x, 'start'])[11:-3]
    data.loc[x, 'stop'] = str(data.loc[x, 'stop'])[11:-3]
    if data.loc[x, 'start'] == data.loc[x, 'stop']: #sleep start and end date are the same, therefore a bad entry
        data.drop(x, inplace = True)#remove bad entry



data['totalSleepTimeMin'] = data['deepSleepTime'] + data["shallowSleepTime"] + data["REMTime"] #add up all sleep time, create new culumn and round to 2 decimals
data['totalSleeptimeHours'] = round(data['totalSleepTimeMin']/60, 2)

C:\Users\kevin\anaconda3\lib\site-packages\pandas\compat\_optional.py:161: UserWarning: Pandas requires version '2.7.1' or newer of 'numexpr' (version '2.7.0' currently installed).
  warnings.warn(msg, UserWarning)
C:\Users\kevin\anaconda3\lib\site-packages\pandas\compat\_optional.py:161: UserWarning: Pandas requires version '1.3.1' or newer of 'bottleneck' (version '1.2.1' currently installed).
  warnings.warn(msg, UserWarning)

In [7]:
#create new file
#data.to_csv('C:/Users/kevin/Documents/Personal/Athletics/SmartWatchData/SleepDataCleaned.csv', index=False)

#add to existing file
#data.to_csv('C:/Users/kevin/Documents/Personal/Athletics/SmartWatchData/SleepDataCleaned.csv', index=False, mode='a', header=False)

In [2]:
data.head()

,date,naps,start,stop,shallowSleepTime,deepSleepTime,REMTime,wakeTime,totalSleepTimeMin,totalSleeptimeHours
0,2022-08-04,0,22:00:,2022-08-04 22:00:00,0,0,0,0,0,0.00
1,2022-08-05,0,22:18:,2022-08-05 08:12:00,255,121,157,61,533,8.88
2,2022-08-06,0,00:33:,2022-08-06 06:52:00,256,61,62,0,379,6.32
3,2022-08-07,0,01:16:,2022-08-07 08:35:00,344,52,43,0,439,7.32
4,2022-08-08,0,03:29:,2022-08-08 08:33:00,162,64,69,9,295,4.92

In [9]:
data.describe()

,shallowSleepTime,deepSleepTime,REMTime,wakeTime,totalSleepTimeMin,totalSleeptimeHours
count,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,281.111111,64.333333,69.000000,7.513889,414.444444,6.907639
std,85.793981,24.564374,31.079181,23.020501,118.493464,1.974640
min,45.000000,12.000000,6.000000,0.000000,63.000000,1.050000
25%,238.500000,49.750000,47.000000,0.000000,346.000000,5.767500
50%,285.500000,63.500000,68.000000,0.000000,423.500000,7.060000
75%,351.000000,79.250000,87.500000,4.250000,499.000000,8.317500
max,444.000000,147.000000,157.000000,140.000000,689.000000,11.480000